### ISSUE TITLE
browsing classes of summary-only ontologies produces error

### ISSUE THREAD

**Issue by alexskr** [ncbo/bioportal_web_ui#133]
browsing classes for summary-only ontology result in "something went wrong error".
Navigating to other pages such as properties, notes, mappings do not produce errors.  
BioPortal should handle this case more gracefully i.e either produce 404 error or redirect all ?p=classes back to the summary page.   Also perhaps default behavior for mappings or properties should change as well.

**Comment by graybeal** [comment]
Was this the related to trying to change an ontology to a summary-only ontology?

**Comment by alexskr** [comment]
yes, it is related to changing ontology to summary-only ontology

**Comment by jvendetti** [comment]
Adding clarification on how this error can be reproduced, which wasn't obvious to me initially.

When ontologies are "Summary Only" and an end user navigates to the Summary page, the UI only displays the Summary and Notes tabs, e.g., see the [Cedar Provisional Classes](https://bioportal.bioontology.org/ontologies/CEDARPC) ontology. Navigating to these Summary Only ontologies doesn't result in any errors, and there is no way for an end user to click on any of the other tabs that would normally be available to non Summary Only ontologies, i.e., Classes, Properties, etc.

Within the confines of BioPortal, the only way to reproduce the 500 error would be to manually modify the URL in the address bar for a Summary Only ontology to include the `?p=classes` query string, e.g.: `/ontologies/CEDARPC?p=classes`. It strikes me as unlikely that an end user would know and/or attempt to do this. Perhaps more likely, is the scenario where a website links to a BioPortal Classes tab for an ontology that used to serve classes, but has since changed to Summary Only.

Output from a GET request to view CEDARPC, showing no errors in the Rails console:

```
Started GET "/ontologies/CEDARPC" for ::1 at 2020-09-02 18:30:48 -0700
Processing by OntologiesController#show as HTML
  Parameters: {"id"=>"CEDARPC"}
  Rendered ontologies/_submissions.html.haml (59.0ms)
  Rendered ontologies/_visits.html.haml (2.1ms)
  Rendered layouts/_topnav.html.haml (5.6ms)
  Rendered layouts/_notices.html.haml (3.7ms)
  Rendered layouts/_header.html.erb (196.6ms)
  Rendered application/_ga_tracking.html.haml (1.0ms)
  Rendered layouts/_footer.html.haml (25.5ms)
  Rendered ontologies/_metadata.html.haml (518.5ms)
Completed 200 OK in 5849ms (Views: 519.8ms | ActiveRecord: 0.0ms)

Started GET "/ontologies/CEDARPC?p=notes&ajax=true" for ::1 at 2020-09-02 18:30:54 -0700
Processing by OntologiesController#show as HTML
  Parameters: {"p"=>"notes", "ajax"=>"true", "id"=>"CEDARPC"}
  Rendered notes/_ontology_list.html.haml (212.3ms)
  Rendered ontologies/_notes.html.erb (217.8ms)
Completed 200 OK in 549ms (Views: 224.4ms | ActiveRecord: 0.0ms)
```
