### ISSUE TITLE
Ontology groups ordering

### ISSUE THREAD

**Issue by graybeal** [ncbo/bioportal_web_ui#15]
Drop-down list of ontology groups is "totally screwy".
* AgroPortal ontologies should not be at the top.
* First should be UMLS, OBO, WHO, CTSA, caBIG, and then it doesn't matter.
* AgroPortal should go last

from https://jira.bmir.stanford.edu/browse/NCBO-1870

**Comment by graybeal** [comment]
Mark writes 3/4/2018:
Incidentally, the categories used to group ontologies should be in order of importance, not the order in which they were added.  It is very weird that agriculture and library science are now at the top of the list!

**Comment by jvendetti** [comment]
I've changed the title and some of the comment text to use "groups" instead of "categories". In BioPortal, categories are used for ontology subject matter, e.g., Anatomy, Health, Imaging, etc. Mark's complaint refers to the ordering of the ontology groups, e.g., OBO Foundry, caBIG, etc.

The drop down list referenced in the initial comment is located on the [home page](http://bioportal.bioontology.org/) (hover over the "Browse Ontologies" link in the "Find an ontology" box.
