### ISSUE TITLE
retire and remove old redirects 

### ISSUE THREAD

**Issue by alexskr** [ncbo/bioportal_web_ui#232]
It is time to retire and remove old redirects which were added 8 years ago.
https://github.com/ncbo/bioportal_web_ui/blob/a80420d4c0272a600c1cb9bdb4568e31eea66181/config/routes.rb#L144-L150

**Comment by alexskr** [comment]
are these also old compatibility redirects and can be removed?
https://github.com/ncbo/bioportal_web_ui/blob/a80420d4c0272a600c1cb9bdb4568e31eea66181/config/routes.rb#L152-L157

**Comment by syphax-bouazzouni** [comment]
If I may add, some notes on this:

- Somme deprectation starting from Rails 7

```
DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 7.1. (called from block in <top (required)> at /app/config/routes.rb:99)
DEPRECATION WARNING: Using a dynamic :controller segment in a route is deprecated and will be removed in Rails 7.1. (called from block in <top (required)> at /app/config/routes.rb:166)
DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 7.1. (called from block in <top (required)> at /app/config/routes.rb:166)

```

- Used js code + routes 
Routes:
https://github.com/ncbo/bioportal_web_ui/blob/a80420d4c0272a600c1cb9bdb4568e31eea66181/config/routes.rb#L109-L110
JS:
https://github.com/ncbo/bioportal_web_ui/blob/a80420d4c0272a600c1cb9bdb4568e31eea66181/app/assets/javascripts/bioportal.js.erb#L435-L467

- Non-existent  controller and action 
https://github.com/ncbo/bioportal_web_ui/blob/a80420d4c0272a600c1cb9bdb4568e31eea66181/config/routes.rb#L112

- Non-existent exibitent action 
https://github.com/ncbo/bioportal_web_ui/blob/a80420d4c0272a600c1cb9bdb4568e31eea66181/config/routes.rb#L157

- Routes not working (not updated since 2013)

https://github.com/ncbo/bioportal_web_ui/blob/a80420d4c0272a600c1cb9bdb4568e31eea66181/config/routes.rb#L152-L157
https://github.com/ncbo/bioportal_web_ui/blob/master/app/controllers/ontologies_controller.rb#L379-L381

**Comment by jvendetti** [comment]
`/exhibit/:ontology/:id` removed in https://github.com/ncbo/bioportal_web_ui/commit/5e63bdc1260fcfa933fd7f05bfc537c1757a8cec
